Create deploy script
bcgov/cas-registration pull request #1292
Opened 2024-04-05 21:42 UTC by BallardRobinett

card: https://github.com/bcgov/cas-reporting/issues/164

Creating a deploy process for the giraffe team to use on the ```giraffe-develop``` branch. 

A bash script ```deploy.sh``` is run from the ```shipit.yaml``` file, which checks if the current branch is ```giraffe-develop``` and runs a different make target to deploy to the CIF-tools namespace (c53ff1-tools). 

Also modified the ```nx-docker-build``` step in our github actions so that aan image is correctly built and pushed to ghcr in our CI and fixed a secret name being generated for the backend.

2024-04-05 23:23 UTC, pbastia requested changes
Nice work! just a couple of things to avoid making changes to the registration code

2024-04-05 23:23 UTC, pbastia commented on client/app/utils/getUserFullName.ts
I don't think we should modify the registration code in place to fix typing issues

The build error comes from the fact that the next-auth `Session` interface has been redefined in `client/app/types/next-auth.d.ts`, and we can fix the build error by including this file in our `tsconfig.json` in the `include` section. I would also be as specific as possible, as this will need to be reverted when we integrate all the apps under the Nx structure.

bceirs/apps/reporting/tsconfig.json
```
...
    "include": [
      ... ,
      "../../../client/app/types/next-auth.d.ts"
    ]
```

2024-04-05 23:23 UTC, pbastia commented on helm/cas-registration/templates/backend/secret.yaml
> +  name: {{ .Release.Name }}-backend
we need to change the `deployment.yaml` file instead to use the helm named template

2024-04-08 19:20 UTC, pbastia commented on bciers/apps/reporting/src/app/api/auth/[...nextauth]/route.ts
> -export const authOptions = regAuthOptions as NextAuthOptions;
Nx enforces the Next conventions and verifies that we're not exporting extra stuff from our routes files

2024-04-08 19:20 UTC, pbastia commented on bciers/yarn.lock
> +"@types/react@*", "@types/react@^18.2.33":
This is to match the registration app down to the minor version, to avoid type incompatibilities

2024-04-08 21:00 UTC, mikevespi approved these changes
Nice work!

2024-04-08 22:00 UTC, pbastia commented on bc_obps/reporting/migrations/0001_initial.py
> +                (
Ooooh good call. I'll add a rule in prettierignore

2024-04-08 23:57 UTC, pbastia commented on bc_obps/reporting/migrations/0001_initial.py
> +                (
on second thought - now that prettier runs on those files, the issue is the files being modified after a release. Prettier _should_ flag this so far

2024-04-08 23:57 UTC, merged