1303 refactor endpoints
bcgov/cas-registration pull request #1400
Opened 2024-04-15 16:09 UTC by BCerki

https://github.com/orgs/bcgov/projects/122/views/2?pane=issue&itemId=59073618
happo diff is flake

2024-04-17 19:08 UTC, Sepehr-Sobhani requested changes
Looks great! 🤩  Just a quick change is needed.

2024-04-17 19:08 UTC, Sepehr-Sobhani commented on bc_obps/service/operator_service.py
> +        cls, existing_parent_operators: List[Operator], updated_parent_operators: List[Operator], user_guid: UUID
The type here should be `List[ParentOperator]`.

2024-04-17 19:56 UTC, BCerki commented on bc_obps/registration/api/operators.py
>  def get_operators_by_cra_number_or_legal_name(
Thanks for catching this!

2024-04-18 15:43 UTC, Sepehr-Sobhani approved these changes
🥇

2024-04-18 15:46 UTC, merged