chore: add k8s liveness and readiness middleware
bcgov/cas-registration pull request #146
Opened 2023-09-27 16:36 UTC by dleard

2023-09-27 22:12 UTC, Sepehr-Sobhani requested changes
Looks great! just some nits :)

2023-09-27 22:12 UTC, Sepehr-Sobhani commented on bc_obps/registration/kubernetesMiddleware.py
nit: I suggest putting this middleware into a folder called middleware to have a place for all middleware (if any down the road) and use the Python folder naming convention for this module.(https://peps.python.org/pep-0008/#package-and-module-names)
Also, I've written a unit test to make sure this middleware works as intended:
```python
from django.http import HttpRequest
from django.test import TestCase
from .middleware.kubernetes_middleware import KubernetesHealthCheckMiddleware


class MiddlewareTestCase(TestCase):
    def test_liveness_endpoint(self):
        middleware = KubernetesHealthCheckMiddleware(None)
        request = HttpRequest()
        request.method = "GET"
        request.path = "/liveness"
        response = middleware(request)

        self.assertEqual(response.status_code, 200)
        self.assertEqual(response.content, b'OK. Server is running.')

    def test_readiness_endpoint(self):
        middleware = KubernetesHealthCheckMiddleware(None)
        request = HttpRequest()
        request.method = "GET"
        request.path = "/readiness"
        response = middleware(request)

        self.assertEqual(response.status_code, 200)
        self.assertEqual(response.content, b'OK. Server is ready.')
`

2023-09-27 22:12 UTC, Sepehr-Sobhani commented on bc_obps/bc_obps/settings.py
> +    'registration.kubernetesMiddleware.KubernetesHealthCheckMiddleware',
We might also need to change this if we decide to change the name of the module and add a middleware folder.

2023-09-28 21:41 UTC, dleard commented on bc_obps/registration/kubernetesMiddleware.py
Would this go in tests.py?

2023-09-28 22:02 UTC, dleard commented on bc_obps/registration/kubernetesMiddleware.py
Created #156 to handle test directory structure & adding this test

2023-09-28 22:21 UTC, Sepehr-Sobhani approved these changes

2023-09-28 22:27 UTC, merged