test: check that newly created operations are visible
bcgov/cas-registration pull request #1604
Opened 2024-05-03 19:29 UTC by BCerki

card: https://github.com/orgs/bcgov/projects/122/views/2?filterQuery=&pane=issue&itemId=61490241

2024-05-10 18:23 UTC, shon-button commented
@BCerki 

I believe your test `e2e/workflows/bceidbusiness/industry_user_admin.spec.ts: line 187` is failing due to incorrect `ButtonText`...awaiting "View Details" but, shows should be "Start Registration"
```
 const brianna = await row.getByRole("link", {
      name: ButtonText.VIEW_DETAILS,
    });
```
![image](https://github.com/bcgov/cas-registration/assets/120038448/6a549516-9c2c-41d1-9f1d-02123ec82e22)

2024-05-10 18:30 UTC, shon-button commented
@BCerki 

As mentioned in PR #1634, the `test.yaml` file needs some changes so to get your failed reports successfully uploaded.

```
  e2e-tests:
    name: 🧪 e2e tests ${{ matrix.project }}
    needs:
      - backend-docker-build
      - nx-docker-build-registration
      - install-dev-tools
    runs-on: ubuntu-latest
    timeout-minutes: 60
    strategy:
      fail-fast: false
      matrix:
        include:
          - project: chromium
            os: ubuntu-latest
            cache_dir: ~/.cache/ms-playwright
          - project: firefox
            os: ubuntu-latest
            cache_dir: ~/.cache/ms-playwright
          - project: webkit
            os: macos-12
            cache_dir: ~/Library/Caches/ms-playwright
    steps:
      - uses: actions/checkout@v4

      - name: 🎁 setup dev env
        uses: ./.github/actions/dev-env-setup

      - name: 🎁 setup local app
        uses: ./.github/actions/local-app-run
        with:
          django_secret_key: ${{ env.DJANGO_SECRET_KEY }}
          keycloak_client_id: ${{ env.KEYCLOAK_CLIENT_ID }}
          keycloak_client_secret: ${{ env.KEYCLOAK_CLIENT_SECRET }}
          nextauth_secret: ${{ env.NEXTAUTH_SECRET }}
      - name: ⚡️ cache Playwright binaries
        uses: actions/cache@v4
        id: playwright-cache
        with:
          path: ${{ matrix.cache_dir }}
          key: ${{ runner.os }}-${{ matrix.project }}-playwright-registration

      - name: 📥 install Playwright ${{ matrix.project }}
        if: steps.playwright-cache.outputs.cache-hit != 'true'
        run: npx playwright install --with-deps ${{ matrix.project }}
        working-directory: ./bciers/apps/registration

      - name: 🎭 Run Playwright Tests
        run: |
          npx happo-e2e -- npx playwright test --project=${{ matrix.project }} bciers/apps/registration/e2e/*
        env:
          API_URL: http://127.0.0.1:8000/api/
          DB_USER: postgres
          DB_NAME: registration
          DB_PORT: 5432
          DB_HOST: localhost
          E2E_BASEURL: http://localhost:3000/
          E2E_CAS_USER: ${{ secrets.E2E_CAS_USER }}
          E2E_CAS_USER_GUID: ${{ secrets.E2E_CAS_USER_GUID }}
          E2E_CAS_USER_PASSWORD: ${{ secrets.E2E_CAS_USER_PASSWORD}}
          E2E_CAS_ADMIN_STORAGE: ${{ secrets.E2E_CAS_ADMIN_STORAGE}}
          E2E_CAS_ANALYST_STORAGE: ${{ secrets.E2E_CAS_ANALYST_STORAGE}}
          E2E_CAS_PENDING_STORAGE: ${{ secrets.E2E_CAS_PENDING_STORAGE}}
          E2E_INDUSTRY_USER_ADMIN: bc-cas-dev
          E2E_INDUSTRY_USER_ADMIN_GUID: ${{ secrets.E2E_INDUSTRY_USER_ADMIN_GUID }}
          E2E_INDUSTRY_USER_ADMIN_PASSWORD: ${{ secrets.E2E_INDUSTRY_USER_ADMIN_PASSWORD }}
          E2E_INDUSTRY_USER_ADMIN_STORAGE: ${{ secrets.E2E_INDUSTRY_USER_ADMIN_STORAGE}}
          E2E_INDUSTRY_USER: bc-cas-dev-secondary
          E2E_INDUSTRY_USER_GUID: ${{ secrets.E2E_INDUSTRY_USER_GUID }}
          E2E_INDUSTRY_USER_PASSWORD: ${{ secrets.E2E_INDUSTRY_USER_PASSWORD }}
          E2E_INDUSTRY_USER_STORAGE: ${{ secrets.E2E_INDUSTRY_USER_STORAGE}}
          E2E_NEW_USER: bc-cas-dev-three
          E2E_NEW_USER_GUID: ${{ secrets.E2E_NEW_USER_GUID }}
          E2E_NEW_USER_PASSWORD: ${{ secrets.E2E_NEW_USER_PASSWORD }}
          E2E_NEW_USER_STORAGE: ${{ secrets.E2E_NEW_USER_STORAGE}}
          HAPPO_API_KEY: ${{ secrets.HAPPO_API_KEY }}
          HAPPO_API_SECRET: ${{ secrets.HAPPO_API_SECRET }}
          HAPPO_NONCE: ${{ github.sha }}
          SMTP_CONNECTION_STRING: smtp://@localhost:1025
        working-directory: ./bciers/apps/registration
      - name: 💾 save ${{ matrix.project }} report artifact
        # prefer to upload the report only in case of test failure
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          # Store all of the reports separately by reconfiguring the report name
          name: blob-report-${{ matrix.project }}
          path: bciers/blob-report
          retention-days: 1
  # Merge the e2e blob reports to one HTML report
  e2e-report:
    name: 📊 e2e report artifact
    runs-on: ubuntu-latest
    needs: [e2e-tests]
    if: ${{ always() && contains(needs.*.result, 'failure') }}
    steps:
      - name: Download blob reports from GitHub Actions Artifacts
        uses: actions/download-artifact@v4
        with:
          path: all-blob-reports
          pattern: blob-report-chromium #blob-report-*
          merge-multiple: true

      - name: Merge into HTML Report
        run: npx playwright merge-reports --reporter html ./all-blob-reports

      - name: Upload HTML report
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report
          retention-days: 14
  # Ensure the e2e tests and e2e report completed successfully
  e2e:
    if: ${{ always() }}
    runs-on: ubuntu-latest
    needs: [e2e-tests]
    steps:
      - run: exit 1
        if: >-
          ${{
               contains(needs.*.result, 'failure')
            || contains(needs.*.result, 'cancelled')
            || contains(needs.*.result, 'skipped')
          }}
```

2024-05-10 21:14 UTC, BCerki commented
> @BCerki
> 
> I believe your test `e2e/workflows/bceidbusiness/industry_user_admin.spec.ts: line 187` is failing due to incorrect `ButtonText`...awaiting "View Details" but, shows "Start Registration"
> 
> ```
>  const brianna = await row.getByRole("link", {
>       name: ButtonText.VIEW_DETAILS,
>     });
> ```
> 
> ![image](https://private-user-images.githubusercontent.com/120038448/329682664-6a549516-9c2c-41d1-9f1d-02123ec82e22.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUzNzUzOTQsIm5iZiI6MTcxNTM3NTA5NCwicGF0aCI6Ii8xMjAwMzg0NDgvMzI5NjgyNjY0LTZhNTQ5NTE2LTljMmMtNDFkMS05ZjFkLTAyMTIzZWM4MmUyMi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUxMFQyMTA0NTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lMTUxNmY4MjBlOTNhMDg2MjViYWIzMDM4ZjQ0ZGU0Y2Q4ZWEzOTExMjQzYmNjMjM2NTBmMzg3OGIxYTMwNDNlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.TikmIJJO9eRazh03hV7Lpod-EOTmPm2A2gauW7AgkDU)

Thank you for this! I think I figured out what's happening. The operation isn't successfully submitting (we can see it didn't go through in this happo shot: 
![image](https://github.com/bcgov/cas-registration/assets/77306764/83d721c3-b0bd-4956-b892-ac9a3c6f2dfc))

So it's "Start Registration" instead of "View Details" because the operation was never submitted, and that's why this test is failing. We have an assertion to check that submission is working but it's not failing so there must be something off about it: `await operationPage.successfulSubmissionIsVisible();`.

2024-05-13 20:18 UTC, BCerki commented on bciers/apps/registration/tsconfig.json
> +    ".next/types/**/*.ts"
This was automatic; I didn't change

2024-05-13 23:36 UTC, Sepehr-Sobhani requested changes
Great work, Thank you 🙏 
Just requested some minor changes.

2024-05-13 23:36 UTC, Sepehr-Sobhani commented on bc_obps/test_media/documents/test.pdf
We need to gitignore `test_media` folder.

2024-05-13 23:36 UTC, Sepehr-Sobhani commented on bc_obps/bc_obps/settings.py
Since we are using `FileSystemStorage`, do we need the below part any longer?

```python
# Using a mock file for e2e testing
use_mock_file = ENVIRONMENT == "develop" and not obj.documents.exists() and obj.status == obj.Statuses.APPROVED
if use_mock_file:
    from registration.tests.utils.helpers import mock_file_to_data_url  # to avoid circular import

    return mock_file_to_data_url()
```

Also, I think we no longer need the `mock_file.pdf` file.

2024-05-14 16:13 UTC, BCerki commented on bc_obps/test_media/documents/test.pdf
I think this was leftover from something I was experimenting with; I just deleted it and it didn't come back

2024-05-14 16:14 UTC, BCerki commented on bc_obps/bc_obps/settings.py
Tests all still pass with this gone

2024-05-14 16:26 UTC, Sepehr-Sobhani approved these changes
🎖️

2024-05-14 16:27 UTC, merged