303 - Activity page - General Stationary Combustion (non-compression and non-processing)
bcgov/cas-registration pull request #2115
Opened 2024-08-21 22:44 UTC by pbastia

2024-08-23 21:56 UTC, dleard requested changes
Looks like this just needs a few source type name swaps. LFO GSC activities have similar sounding, but different source type names.
Tests are a nice addition!

2024-08-23 21:56 UTC, dleard commented on bc_obps/reporting/json_schemas/2024/gsc_non_compression_non_combustion/with_useful_energy.json
> +  "title": "General stationary combustion of fuel or waste with production of useful energy",
```suggestion
  "title": "General stationary combustion of fuel or waste at a linear facilities operation resulting in the production of useful energy",
```
The LFO GSC activities have similar, but different source types

2024-08-23 21:56 UTC, dleard commented on bc_obps/reporting/json_schemas/2024/gsc_non_compression_non_combustion/without_useful_energy.json
> +  "title": "General stationary combustion of waste without production of useful energy",
```suggestion
  "title": "General stationary combustion of fuel or waste at a linear facilities operation not resulting in the production of useful energy",
```
same as above

2024-08-23 21:56 UTC, dleard commented on bc_obps/reporting/migrations/0007_reinit.py
> +        migrations.AddConstraint(
:+1:

2024-08-23 21:56 UTC, dleard commented on bc_obps/reporting/tests/models/program_configuration_tests/test_gsc_non_compression_non_processing_2024.py
> +            'General stationary combustion of waste without production of useful energy': gas_config,
```suggestion
            'General stationary combustion of fuel or waste at a linear facilities operation not resulting in the production of useful energy': gas_config,
```

2024-08-23 21:56 UTC, dleard commented on bc_obps/reporting/tests/models/program_configuration_tests/test_gsc_non_compression_non_processing_2024.py
> +            'General stationary combustion of fuel or waste with production of useful energy': gas_config,
```suggestion
            'General stationary combustion of fuel or waste at a linear facilities operation resulting in the production of useful energy': gas_config,
```

2024-08-23 21:56 UTC, dleard commented on bciers/apps/reporting/src/app/components/activities/uiSchemas/gscNonCompressionNonProcessingUiSchema.ts
> +  gscWithProductionOfUsefulEnergy: {
```suggestion
  gscWithProductionOfUsefulEnergy: {
```
gscFuelOrWasteLinearFacilitiesUsefulEnergy

2024-08-23 21:56 UTC, dleard commented on bciers/apps/reporting/src/app/components/activities/uiSchemas/gscNonCompressionNonProcessingUiSchema.ts
> +  gscWithoutProductionOfUsefulEnergy: {
```suggestion
  gscFuelOrWasteLinearFacilitiesWithoutUsefulEnergy: {
```

2024-08-23 21:56 UTC, dleard commented on bciers/apps/reporting/src/app/components/activities/uiSchemas/gscNonCompressionNonProcessingUiSchema.ts
> +    gscWithProductionOfUsefulEnergy: {
```suggestion
    gscFuelOrWasteLinearFacilitiesUsefulEnergy: {
```

2024-08-23 21:56 UTC, dleard commented on bciers/apps/reporting/src/app/components/activities/uiSchemas/gscNonCompressionNonProcessingUiSchema.ts
> +    gscWithoutProductionOfUsefulEnergy: {
```suggestion
    General stationary combustion of fuel or waste at a linear facilities operation not resulting in the production of useful energy: {
```

2024-08-23 21:56 UTC, dleard commented on bc_obps/reporting/migrations/0014_gsc_non_compression_non_processing.py
All the source type names will need to be swapped in this file as above, should just need a quick search & replace

2024-09-04 22:33 UTC, dleard approved these changes
Nice! I think we should add a tech-debt card to add tests to the activities we've already done, using these tests as a template & make sure that any new activity configurations are also tested

2024-09-04 22:34 UTC, merged

2024-09-04 22:35 UTC, pbastia commented
Sounds good! I'll write a card.