feat:Activity-Hydrogen Production
bcgov/cas-registration pull request #2183
Opened 2024-09-11 17:22 UTC by ayeshmcg

Hydrogen Production Activity Page - Draft

2024-09-16 19:06 UTC, dleard requested changes
Nice! It all works correctly, just a few changes needed & I've tagged a couple other devs in places where I have questions for them to weigh in on

2024-09-17 00:56 UTC, ayeshmcg commented on bciers/apps/reporting/src/app/components/activities/hydrogenProduction.tsx
> +    emissions: [{ gasType: "CO2" }],
@dleard  Removed this for now

2024-09-18 00:16 UTC, ayeshmcg commented on bc_obps/reporting/migrations/0016_custom_methodology_schema.py
> +        ('registration', '0040_alter_facility_address_and_more'),
@dleard shall I keep this for now?

2024-09-19 15:45 UTC, Sepehr-Sobhani commented on bc_obps/reporting/migrations/0016_custom_methodology_schema.py
> +        ('registration', '0040_alter_facility_address_and_more'),
If Django added the dependency automatically, it's best to keep it. Django uses the dependency array to build a dependency graph, so it's usually best not to manually update migration files unless you really need to.

2024-09-19 23:04 UTC, dleard commented on bc_obps/reporting/tests/models/program_configuration_tests/test_hydrogen_production_2024.py
> +    def testCustomMethodologySchema(self):
:heart:

2024-09-19 23:26 UTC, dleard approved these changes
Looks great! Thanks for all your work on the custom methodology schema stuff, that unblocks a couple other activities now that will also need it :)

2024-09-19 23:26 UTC, merged