Feat/255 select person responsible
bcgov/cas-registration pull request #2353
Opened 2024-10-09 16:11 UTC by ayeshmcg

Card: https://github.com/bcgov/cas-reporting/issues/255
Changes:

Added Person Resposible Page
Added Person Resposible Page
Added Model for report person responsible
Added API

To test:-
Go to page /reporting/reports after logging in with BCeId
Select any operation
It wil open operation reveiw information page and then click on save and Coninue, it wil take you to /reporting/reports/{report_version}/person-responsible page
If there are any previously selected person resposible for the report it will pre-populate the contact details, if not select any contact and save.

2024-10-09 21:02 UTC, dleard requested changes
Tested it locally & it works great! A few minor changes needed & then this should be good to go! :100:

2024-10-09 21:19 UTC, ayeshmcg commented on bciers/apps/reporting/src/app/bceidbusiness/industry_user_admin/reports/[version_id]/person-responsible/page.tsx
> +  console.log("versionId", params.version_id);
missed that,

2024-10-09 21:20 UTC, ayeshmcg commented on bciers/apps/reporting/src/app/components/operations/personResponsible/PersonResponsible.tsx
> +  const saveAndContinueUrl = `/reports/${version_id}/review-facilities`;
So we need to get the facilityId for this , right?

2024-10-09 21:24 UTC, dleard commented on bciers/apps/reporting/src/app/components/operations/personResponsible/PersonResponsible.tsx
> +  const saveAndContinueUrl = `/reports/${version_id}/review-facilities`;
Yeah, it'll have to be fetched from the report_version

2024-10-09 22:10 UTC, pbastia commented on bc_obps/service/report_service.py
> +        return cast(ReportPersonResponsibleOut, report_person_responsible)
nope! Django-ninja does this for us, it's magic!

2024-10-09 22:19 UTC, ayeshmcg commented on bc_obps/service/report_service.py
> +
@dleard What about creating report_person_responsible_service?

2024-10-11 00:42 UTC, ayeshmcg commented
@dleard  Added check for operation type as well, if LFO-> it will show a page with TBD

2024-10-11 20:00 UTC, dleard requested changes

2024-10-11 20:00 UTC, dleard commented on bc_obps/reporting/api/facility_report.py
Looks like this file got messed up a little bit during a rebase. The activity-list endpoint was removed & there are some regressions with the return types/values for get/save facility_report

2024-10-15 17:38 UTC, dleard approved these changes
Really nice work! A couple minor things around permissions to fix up and then this is good to merge

2024-10-15 17:38 UTC, dleard commented on bc_obps/reporting/api/report_person_responsible.py
> +    auth=authorize("approved_authorized_roles"),
This permissions should be scoped to the `approved_industry_user` as an idir user should not be able to mutate the contents of a report.
```suggestion
    auth=authorize("approved_industry_user"),
```

2024-10-15 17:38 UTC, dleard commented on bc_obps/reporting/api/reports.py
> +    auth=authorize("approved_authorized_roles"),
Same thing here
```suggestion
    auth=authorize("approved_industry_user"),
```

2024-10-15 17:38 UTC, dleard commented on bc_obps/reporting/models/report_person_responsible.py
> +    # A report version can have multiple persons responsible
Is this comment correct? I thought a report version can only have one person responsible?

2024-10-15 17:38 UTC, dleard commented on bciers/apps/reporting/src/app/components/operations/personResponsible/PersonResponsible.tsx
> +      console.log("facilityReport", facilityReport);
Remove debugging line

2024-10-16 21:03 UTC, merged