2627 improve mock data
bcgov/cas-registration pull request #2636
Opened 2024-12-20 23:16 UTC by BCerki

card: https://github.com/orgs/bcgov/projects/123/views/16?pane=issue&itemId=91540613&issue=bcgov%7Ccas-registration%7C2627

2024-12-20 23:51 UTC, BCerki commented on bc_obps/registration/fixtures/mock/operation.json
> +      "point_of_contact": 1,
I got errors when I removed this, but I don't think it's supposed to be used in reg2, to investigate

2025-01-10 20:32 UTC, Sepehr-Sobhani requested changes

2025-01-10 21:03 UTC, BCerki commented on bc_obps/registration/fixtures/mock/facility.json
> +      "longitude_of_largest_emissions": -123.5
Do you mean "Small Aggregate"? We won't be able to remove lat/long until https://github.com/bcgov/cas-registration/pull/2653 is in (where they're made optional)

2025-01-10 21:08 UTC, BCerki commented on bc_obps/registration/fixtures/mock/operation.json
> +      "point_of_contact": 1,
We can handle this in the contacts migration ticket: https://github.com/orgs/bcgov/projects/123/views/16?filterQuery=repo%3Abcgov%2Fcas-registration+-status%3Adone+contact&pane=issue&itemId=93316267&issue=bcgov%7Ccas-registration%7C2672. I've added an AC to update mock data

2025-01-10 21:09 UTC, Sepehr-Sobhani commented on bc_obps/registration/fixtures/mock/facility.json
> +      "longitude_of_largest_emissions": -123.5
Yes, Sorry my bad! 
I think that PR will be merged sooner than this PR.

2025-01-10 21:13 UTC, BCerki commented on bc_obps/registration/fixtures/mock/operation.json
> +      "status": "Closed",
All the statuses in the reg1 mock data (bc_obps/registration/fixtures/mock/v1/operation.json) can stay as is to pass CI, but for reg2 mocks, yes, we should only have statuses that are in the Operation model

2025-01-10 21:33 UTC, BCerki commented on bc_obps/registration/fixtures/mock/operation.json
> +      "name": "Banana LFO - Registered",
For this AC: All LFO operations (except one) should have at least two facilities
LFOs without facilities shouldn't be registered (though I don't think we enforce this). Can we change the status and name of whichever one doesn't have facilities?

2025-01-10 21:37 UTC, BCerki commented on bc_obps/registration/fixtures/mock/facility.json
> +      "longitude_of_largest_emissions": -123.5
Merged now!

2025-01-10 21:37 UTC, BCerki commented on bc_obps/registration/fixtures/mock/facility.json
> +      "bcghg_id": "13219990029",
Can we remove bcghg_id from some of the facilities? This will make it easier for testers to assign them

2025-01-10 21:41 UTC, BCerki commented on bc_obps/registration/fixtures/mock/facility.json
> +      "created_by": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
Related, we should update the `bceid_business_name` in `cas-registration/bc_obps/registration/fixtures/mock/user.json` to match any changed operator names

2025-01-10 22:00 UTC, BCerki commented on bc_obps/registration/fixtures/mock/facility_designated_operation_timeline.json
> +  },
We either need to update both timeline fixtures to match the transfer_event fixture, or change that to match this

2025-01-10 22:10 UTC, Sepehr-Sobhani commented on bc_obps/registration/fixtures/mock/facility_designated_operation_timeline.json
> +  },
I suggest prioritizing the population of timeline tables first, as they are more critical. The transfer_event fixtures can be handled afterward as the final step.

2025-01-10 22:45 UTC, BCerki reviewed
I think Bojangles SFO might be missing a facility because we see "Edit Details" in the grid: 
![image](https://github.com/user-attachments/assets/f0d96c69-1c6f-4da0-9462-1bc981ba0726)

2025-01-13 21:05 UTC, fviduya commented on bc_obps/registration/fixtures/mock/facility.json
> +      "created_by": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
@BCerki, I saw the thread in Teams about whether bceid_business_name is related to operator legal name, and I had the same question. Is my understanding correct that it's not _exactly_ the same (but technically they are?) and there can be subtle differences, but do you guys want me to just go ahead and update bceid_business_name to reflect the changed operator names?

2025-01-13 22:07 UTC, BCerki commented on bc_obps/registration/fixtures/mock/facility.json
> +      "created_by": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
Yes, let's make them match the operator names for the purposes of mock data

2025-01-13 22:37 UTC, fviduya commented on bc_obps/registration/fixtures/mock/operation.json
> +      "name": "Banana LFO - Registered",
There are 2 LFO operations in the file, this (Banana) and Apple. Apple has only 1 facility registered, Banana has 20 registered. Would you prefer to remove the facility registered in Apple so it doesn't have anything under it and I can change the Status and Name to reflect that?

2025-01-13 22:39 UTC, BCerki commented on bc_obps/registration/fixtures/mock/operation.json
> +      "name": "Banana LFO - Registered",
Sure, or we can make a third LFO with no facilities, whatever's easiest

2025-01-14 00:53 UTC, fviduya commented on bc_obps/registration/fixtures/mock/facility.json
> +      "longitude_of_largest_emissions": -123.5
I tried removing this on my end but it failed when I ran make reset_reg_data, realized because I haven't gotten the code from develop yet. So I'll be removing the long/lat from Small Aggregate once the code's updated

2025-01-14 00:54 UTC, fviduya commented on bc_obps/registration/fixtures/mock/facility_designated_operation_timeline.json
> +      "created_by": "00000000-0000-0000-0000-000000000001",
I've fixed this by changing the operator, I put Bojangles' pk instead since that one's missing the facility. Please let me know if the data is still inconsistent 😄

2025-01-14 00:54 UTC, fviduya commented on bc_obps/registration/fixtures/mock/operation.json
> +      "status": "Closed",
I'm not sure how I got some statuses that are not part of the model, I don't recall anymore sorry about that!

2025-01-14 01:00 UTC, fviduya commented
Thank you for the thorough review! I realized that some of the data might've gotten incorrect because of the merge conflict I tried to fix last time. 

[This commit](https://github.com/bcgov/cas-registration/pull/2636/commits/3b4f50bcf568418ff4549d8f7a3324ef93fe9f91) addresses these:

- [x] Fix operation_designated_operator_timeline to reflect correct data
- [x] Update boro ID (24 since created in 2024)
- [x] Fix Status in Operation.json to reflect only Statuses available in model
- [x] Fix operator.json BORO ID
- [x] Update bceid_business_name to match any changed operator names
- [x] Check created_by field from facility.json and ensure that user is not in Pending Status
- [x] Remove half of the bcghg_id from facility.json

While I was fixing the code, I did have some questions:
- For operation_designated_operator_timeline: Does the created_by need to be in sync with user_operator?
- If the user_operator is in Pending status, is it allowed to have a record in the operation_designated_operator_timeline?

2025-01-14 21:12 UTC, Sepehr-Sobhani requested changes

2025-01-14 21:12 UTC, Sepehr-Sobhani commented on bc_obps/registration/fixtures/mock/operation_designated_operator_timeline.json
User `00000000-0000-0000-0000-000000000004` has a pending access request to operator `685d581b-5698-411f-ae00-de1d97334a71` so we can't use this user for `created_by` fields in this fixture.

2025-01-15 00:59 UTC, fviduya commented
[This commit](https://github.com/bcgov/cas-registration/pull/2636/commits/c4ed19940b4cf5f12d96dd888784e86624555fb4) 
- ensures that the BORO ID number corresponds to the year it was created
- better distribution of bcghg_id among the facilities
- fixes status of user_operator
- ensures realistic user in operator_designated_operation_timeline

2025-01-15 18:55 UTC, Sepehr-Sobhani requested changes

2025-01-17 16:20 UTC, Sepehr-Sobhani approved these changes
🤩 Great work!

2025-01-17 18:15 UTC, merged