Chore: add role table
bcgov/cas-registration pull request #287
Opened 2023-11-16 23:36 UTC by dleard

card: 281

2023-11-17 00:18 UTC, Sepehr-Sobhani requested changes
Looks great! a couple of minor changes are required.

2023-11-17 00:18 UTC, Sepehr-Sobhani commented on bc_obps/registration/models.py
> +        related_name="user_app_role",
I suggest using plural names for related objects, as it retrieves multiple records from an `AppRole` instance rather than just one.

2023-11-17 00:18 UTC, Sepehr-Sobhani commented on bc_obps/registration/models.py
I suggest that we populate some data in `AppRole` table, either by using a fixture or providing a function to the migration file. We can then use the ID of the created `AppRole` instance as a foreign key in the user fixture for the user instances. This will ensure that the data is properly associated and avoids any issues with data integrity.

2023-11-18 01:09 UTC, dleard commented on bc_obps/registration/models.py
There is a function in the migration file to populate initial data for the app_role table. The call is [here](https://github.com/bcgov/cas-registration/pull/287/files#diff-ef16f115cd68f3e0b2e49884c2b5e89844efff57b1430f32838d08b7f4ec004bR60)

2023-11-18 01:15 UTC, Sepehr-Sobhani approved these changes
Looks great! We just need to use the PK of roles in the user fixture file.

2023-11-18 01:15 UTC, Sepehr-Sobhani commented on bc_obps/registration/models.py
Sorry, I must have missed that. This looks great, we just need to use the PK of these roles in the user fixture file.

2023-11-18 01:25 UTC, dleard commented on bc_obps/registration/models.py
I think I did that too? [here](https://github.com/bcgov/cas-registration/pull/287/files#diff-3d01cf820f7873ded05eefa3e55965df3ab06a063bae1d2ff0af1f3e457696eeR17).

2023-11-18 01:25 UTC, merged

2023-11-18 01:27 UTC, Sepehr-Sobhani commented on bc_obps/registration/models.py
Ok, I think I'm tired and should leave ASAP :D