173 number widget
bcgov/cas-registration pull request #324
Opened 2023-11-23 22:53 UTC by marcellmueller

- refactor: move shared widget styles to mui theme
- feat: rjsf set number input based on field type
- feat: remove number input arrows globally
- docs: add rjsf number type documentation

2023-11-27 23:36 UTC, andrea-williams requested changes
Was playing around with this widget. For the new Operation form I entered an unrealistically large number for 2022 emissions and then hit Submit. On the frontend I just got a "HTTP error! Status: 500" message at the bottom of the screen, and no error is displayed next to the specific field. But looking at my logs I see this error:
"psycopg.errors.NumericValueOutOfRange: numeric field overflow
DETAIL:  A field with precision 10, scale 5 must round to an absolute value less than 10^5"
Because our numeric columns in the database have a max precision 10, scale 5, I'd recommend that we add a max limit to the number widget so that values exceeding that display an error on the frontend.

2023-11-27 23:43 UTC, marcellmueller commented
> Was playing around with this widget. For the new Operation form I entered an unrealistically large number for 2022 emissions and then hit Submit. On the frontend I just got a "HTTP error! Status: 500" message at the bottom of the screen, and no error is displayed next to the specific field. But looking at my logs I see this error: "psycopg.errors.NumericValueOutOfRange: numeric field overflow DETAIL: A field with precision 10, scale 5 must round to an absolute value less than 10^5" Because our numeric columns in the database have a max precision 10, scale 5, I'd recommend that we add a max limit to the number widget so that values exceeding that display an error on the frontend.

We can add max length easily but if I understand correctly `10^5` is `100000`? We might have to add per field max length as hardcoding in a max of 100k doesn't seem right.

2023-11-28 00:01 UTC, andrea-williams commented
> > Was playing around with this widget. For the new Operation form I entered an unrealistically large number for 2022 emissions and then hit Submit. On the frontend I just got a "HTTP error! Status: 500" message at the bottom of the screen, and no error is displayed next to the specific field. But looking at my logs I see this error: "psycopg.errors.NumericValueOutOfRange: numeric field overflow DETAIL: A field with precision 10, scale 5 must round to an absolute value less than 10^5" Because our numeric columns in the database have a max precision 10, scale 5, I'd recommend that we add a max limit to the number widget so that values exceeding that display an error on the frontend.
> 
> We can add max number easily but if I understand correctly `10^5` is `100000`? We might have to add per field max as hardcoding in a max of 100k doesn't seem right.

ahh yes you make a good point. I think there is a problem with our current definition of the previous_year_emissions column in our operation table - that's a separate issue outside the scope of this PR. 

For this PR, could we set a max number of 2147483647 (the maximum integer value that Postgres supports) please?

2023-11-28 00:25 UTC, marcellmueller commented
> ahh yes you make a good point. I think there is a problem with our current definition of the previous_year_emissions column in our operation table - that's a separate issue outside the scope of this PR.
> 
> For this PR, could we set a max number of 2147483647 (the maximum integer value that Postgres supports) please?

Sounds good, I've added a max number and it will be easy to set an option to do a per field max in the future. I think we will need to go over the number fields and add a max number, I will try to remember to make a ticket tomorrow morning.

2023-11-28 00:28 UTC, andrea-williams commented
> > ahh yes you make a good point. I think there is a problem with our current definition of the previous_year_emissions column in our operation table - that's a separate issue outside the scope of this PR.
> > For this PR, could we set a max number of 2147483647 (the maximum integer value that Postgres supports) please?
> 
> Sounds good, I've added a max number and it will be easy to set an option to do a per field max in the future. I think we will need to go over the number fields and add a max number, I will try to remember to make a ticket tomorrow morning.

I just checked with Hanna - she agrees that our configuration for that DB column is off. I've created a new ticket to make changes to the DB. Setting the max value of the number widget to be equal to the max integer value in Postgres should be good enough for now.

2023-11-28 23:15 UTC, merged