280 multiple operators
bcgov/cas-registration pull request #350
Opened 2023-11-28 19:02 UTC by marcellmueller

Implements #280 

Note: currently if you save the form with multiple operators, then remove them and save the form again they will still appear in the form data. I have created issue #361 to handle this as it is blocked on #326 to implement.

This includes major changes to the `operators` form including moving the multiple operators section to page 1 as in the Figma designs. The multiple operators form is revealed if you choose `Yes` for the question `Does the operation have multiple operators?` at the bottom of page 1. You can add as many operators as you want if you click the `Add another operator` button.

<img width="968" alt="Screenshot 2023-12-05 at 1 57 48 PM" src="https://github.com/bcgov/cas-registration/assets/14259474/fd2a1523-9fb4-4ec0-a0bd-62f265e6cf16">

2023-12-06 22:00 UTC, dleard requested changes

2023-12-06 22:12 UTC, marcellmueller commented on bc_obps/registration/models.py
> +    mailing_address_same_as_physical = models.BooleanField(
These actually do need to be a column in the table or else the form displays incorrectly as this data is lost after saving and reloading.

2023-12-06 22:39 UTC, marcellmueller commented on bc_obps/registration/migrations/0001_initial.py
> +                    models.ForeignKey(
Thanks, updated!

2023-12-06 22:41 UTC, marcellmueller commented on bc_obps/registration/models.py
> +    business_structure = models.CharField(
Ah yeah I should have wrote a comment about this. At the time I was working on this PR the business structure functionality for the user operator form was being worked on in another PR so I left this. 

I started to update this though I think I should do it in a separate PR to make it easier to review.

2023-12-06 22:46 UTC, marcellmueller commented on client/app/components/form/OperationsForm.tsx
>                operator_id: 1,
It needs to be there for the form to submit. How do I go about getting the operator id?

2023-12-07 00:03 UTC, dleard commented on bc_obps/registration/models.py
> +    mailing_address_same_as_physical = models.BooleanField(
Ah, yeah makes sense

2023-12-08 23:16 UTC, dleard approved these changes
Looks like it needs a rebase, but otherwise good to go (unless you're going to tackle the change to 'business_structure' in this PR rather than a subsequent one)

2023-12-11 16:36 UTC, merged