379 delete rejected prime admin
bcgov/cas-registration pull request #613
Opened 2024-01-17 22:38 UTC by Sepehr-Sobhani

[CARD 379](https://github.com/orgs/bcgov/projects/122/views/2?pane=issue&itemId=48609618)

2024-01-19 19:17 UTC, andrea-williams commented
Updates based on recent discussion with Hanna:

- IRC will want to still see rejected prime admin requests, in case external users contact them to follow up on access requests
- the "Senior Officer" part of the form will be removed as part of MVP (IRC no longer needs it) - this might mean this PR is no longer needed? I haven't read through the code for this PR yet - let me know if I should @Sepehr-Sobhani !

2024-01-19 21:12 UTC, Sepehr-Sobhani commented
> Updates based on recent discussion with Hanna:
> 
> * IRC will want to still see rejected prime admin requests, in case external users contact them to follow up on access requests
> * the "Senior Officer" part of the form will be removed as part of MVP (IRC no longer needs it) - this might mean this PR is no longer needed? I haven't read through the code for this PR yet - let me know if I should @Sepehr-Sobhani !

@andrea-williams 
- Thanks for confirming.
- I think this PR is still valid because we are refactoring a bunch of code here but we need a separate task ticket to remove the SO part from the code.

2024-01-19 23:46 UTC, andrea-williams commented on bc_obps/registration/api/user_operator.py
> +        return 400, {"message": "Operator must be approved before approving users."}
The logic here will need to be modified. In cases where the operator data has been imported from CIIP/SWRS, its status will be "DRAFT" at the time that a user is requesting prime admin. The user will need to have admin access to the operator before they're able to update/confirm the imported data about the Operator, at which point the Operator's status will be set to Pending/Accepted.

(see the "Andrea's brain dumping ground" Miro board for a map of this workflow if you need more context)

2024-01-19 23:57 UTC, andrea-williams requested changes
Just the one change request (related to my comment in `user_operator.py`). I think the fix is as simple as changing
`if user_operator.operator.status != Operator.Statuses.APPROVED:`
to

`if user_operator.operator.status is in [Operator.Statuses.PENDING, Operator.Statuses.REJECTED]:`

2024-01-22 18:02 UTC, Sepehr-Sobhani commented
> Just the one change request (related to my comment in `user_operator.py`). I think the fix is as simple as changing `if user_operator.operator.status != Operator.Statuses.APPROVED:` to
> 
> `if user_operator.operator.status is in [Operator.Statuses.PENDING, Operator.Statuses.REJECTED]:`

I thought users always have to approve the operator first and then they will be prompted to approve the admin request!

2024-01-22 18:07 UTC, andrea-williams commented
> > Just the one change request (related to my comment in `user_operator.py`). I think the fix is as simple as changing `if user_operator.operator.status != Operator.Statuses.APPROVED:` to
> > `if user_operator.operator.status is in [Operator.Statuses.PENDING, Operator.Statuses.REJECTED]:`
> 
> I thought users always have to approve the operator first and then they will be prompted to approve the admin request!

When it's a newly created operator (i.e., one that hasn't been imported from CIIP/SWRS), an internal user will have to approve the new operator first before approving the admin request. But when it's an operator that has been imported from existing data, we need to approve the admin request first before we allow that external user to review the imported Operator data and update any fields that have changed.

I hope this makes sense - if not, happy to hop on a call to discuss it :)

2024-01-22 18:15 UTC, Sepehr-Sobhani commented
> > > Just the one change request (related to my comment in `user_operator.py`). I think the fix is as simple as changing `if user_operator.operator.status != Operator.Statuses.APPROVED:` to
> > > `if user_operator.operator.status is in [Operator.Statuses.PENDING, Operator.Statuses.REJECTED]:`
> > 
> > 
> > I thought users always have to approve the operator first and then they will be prompted to approve the admin request!
> 
> When it's a newly created operator (i.e., one that hasn't been imported from CIIP/SWRS), an internal user will have to approve the new operator first before approving the admin request. But when it's an operator that has been imported from existing data, we need to approve the admin request first before we allow that external user to review the imported Operator data and update any fields that have changed.
> 
> I hope this makes sense - if not, happy to hop on a call to discuss it :)

Gotcha, Thanks for the clarification.

2024-01-22 19:06 UTC, andrea-williams commented on bc_obps/registration/api/user_operator.py
> +    # We can't update the status of a user_operator if the operator is not approved
```suggestion
    # We can't update the status of a user_operator if the operator has been declined or is awaiting review
```

2024-01-22 19:25 UTC, merged