591 draft tile
bcgov/cas-registration pull request #736
Opened 2024-01-26 17:25 UTC by BCerki

https://github.com/orgs/bcgov/projects/122/views/2?pane=issue&itemId=50184016

2024-01-29 22:46 UTC, BCerki commented on client/middlewares/operatorRedirectMiddeware.tsx
> +    console.log("pathname", pathname);
I oould only ever get:
pathname /api/auth/token
pathname /api/auth/session

2024-01-30 21:01 UTC, shon-button commented on client/app/components/layout/Tiles.tsx
Since the tile imports are not longer needed to be "dynamic", I think regular imports can be done (at the top of the file and not in the useEffect)

2024-01-30 21:01 UTC, shon-button commented on client/app/components/layout/Tiles.tsx
I wonder if this component is more `navigation` over `layout` ?

2024-01-30 21:03 UTC, shon-button commented
@BCerki to test 
```
Given I am an external user with access to an Operator
When my Operator's status = "Draft"
Then I CANNOT access the Operations tile on my dashboard without first navigating to the "My Operator" tile and confirming (or updating) the imported Operator data.
```
is there a login ID I should use (that has the condition fixtures in place), or do I have to setup the conditions in my local db?
thanks :)

2024-01-31 14:21 UTC, BCerki commented
> @BCerki to test
> 
> ```
> Given I am an external user with access to an Operator
> When my Operator's status = "Draft"
> Then I CANNOT access the Operations tile on my dashboard without first navigating to the "My Operator" tile and confirming (or updating) the imported Operator data.
> ```
> 
> is there a login ID I should use (that has the condition fixtures in place), or do I have to setup the conditions in my local db? thanks :)

No login ID; you'll have to set up the conditions locally

2024-02-01 15:30 UTC, shon-button commented
**TEST**
```
Given I am an external user with access to an Operator
When my Operator's status = "Draft"
Then I CANNOT access the Operations tile on my dashboard without first navigating to the "My Operator" tile and confirming (or updating) the imported Operator data.
```
**Steps**
1. Set `bc_obps/registration/fixtures/mock/userOperator.json` JSON as follows:
```
{
    "model": "registration.useroperator",
    "pk": 2,
    "fields": {
      "user": "ba2ba62a....",
      "operator": 2,
      "role": "admin",
      "status": "Draft",
      "verified_at": null,
      "verified_by": null
    }
  },
```
2. Run `make reset_db`
3. Navigate to: `http://localhost:3000/dashboard/select-operator`
4. Search "Existing Operator 2 Legal Name": ` "GET /api/registration/operators/legal-name?search_value=Existing%20Operator%202%20Legal%20Name HTTP/1.1" 200`
5. Request Access : `"POST /api/registration/select-operator/request-access HTTP/1.1" 201`
6. Errors:
```
An error occurred while fetching registration/operator-has-admin/2: SyntaxError: Unexpected token < in JSON at position 1
    at JSON.parse (<anonymous>)
    at parseJSONFromBytes (node:internal/deps/undici/undici:6662:19)
    at successSteps (node:internal/deps/undici/undici:6636:27)
    at node:internal/deps/undici/undici:1236:60
    at node:internal/process/task_queues:140:7
    at AsyncResource.runInAsyncScope (node:async_hooks:203:9)
    at AsyncResource.runMicrotask (node:internal/process/task_queues:137:8)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
An error occurred while fetching registration/operators/2: SyntaxError: Unexpected token < in JSON at position 1
    at JSON.parse (<anonymous>)
    at parseJSONFromBytes (node:internal/deps/undici/undici:6662:19)
    at successSteps (node:internal/deps/undici/undici:6636:27)
    at node:internal/deps/undici/undici:1236:60
    at node:internal/process/task_queues:140:7
    at AsyncResource.runInAsyncScope (node:async_hooks:203:9)
    at AsyncResource.runMicrotask (node:internal/process/task_queues:137:8)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
An error occurred while fetching registration/operator-has-admin/2: SyntaxError: Unexpected token < in JSON at position 1
    at JSON.parse (<anonymous>)
    at parseJSONFromBytes (node:internal/deps/undici/undici:6662:19)
    at successSteps (node:internal/deps/undici/undici:6636:27)
    at node:internal/deps/undici/undici:1236:60
    at node:internal/process/task_queues:140:7
    at AsyncResource.runInAsyncScope (node:async_hooks:203:9)
    at AsyncResource.runMicrotask (node:internal/process/task_queues:137:8)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
An error occurred while fetching registration/user-operator-id: SyntaxError: Unexpected token < in JSON at position 1
    at JSON.parse (<anonymous>)
    at parseJSONFromBytes (node:internal/deps/undici/undici:6662:19)
    at successSteps (node:internal/deps/undici/undici:6636:27)
    at node:internal/deps/undici/undici:1236:60
    at node:internal/process/task_queues:140:7
    at AsyncResource.runInAsyncScope (node:async_hooks:203:9)
    at AsyncResource.runMicrotask (node:internal/process/task_queues:137:8)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
An error occurred while fetching registration/user-operator-status-from-user: SyntaxError: Unexpected token < in JSON at position 1
    at JSON.parse (<anonymous>)
    at parseJSONFromBytes (node:internal/deps/undici/undici:6662:19)
    at successSteps (node:internal/deps/undici/undici:6636:27)
    at node:internal/deps/undici/undici:1236:60
    at node:internal/process/task_queues:140:7
    at AsyncResource.runInAsyncScope (node:async_hooks:203:9)
    at AsyncResource.runMicrotask (node:internal/process/task_queues:137:8)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
An error occurred while fetching registration/operators?legal_name=Existing Operator 2 Legal Name: SyntaxError: Unexpected token < in JSON at position 1
    at JSON.parse (<anonymous>)
    at parseJSONFromBytes (node:internal/deps/undici/undici:6662:19)
    at successSteps (node:internal/deps/undici/undici:6636:27)
    at node:internal/deps/undici/undici:1236:60
    at node:internal/process/task_queues:140:7
    at AsyncResource.runInAsyncScope (node:async_hooks:203:9)
    at AsyncResource.runMicrotask (node:internal/process/task_queues:137:8)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

```

2024-02-01 15:36 UTC, shon-button commented
**FYI**
Not part of your PR but, there is a `print(user_operator)` statement in `bc_obps/registration/api/user_operator.py` line 173

2024-02-01 15:51 UTC, shon-button commented on client/app/data/dashboard/bceid/users.json
Missing `➤` in link\title "User Access Management"

2024-02-01 17:14 UTC, shon-button requested changes

2024-02-01 17:14 UTC, shon-button commented on client/middlewares/withAuthorization.tsx
Error `TypeError: Failed to parse URL from registration/operator-from-user @ middlewares/withAuthorization.tsx (119:37) @ fetch` when navigating to `http://localhost:3000/dashboard/operations`

2024-02-01 17:14 UTC, shon-button commented on client/middlewares/withAuthorization.tsx
Could we use `client/app/utils/actions.ts\ return Sentry.withServerActionInstrumentation` for the fetch call?

2024-02-01 17:38 UTC, shon-button requested changes

2024-02-01 17:38 UTC, shon-button commented on client/app/components/form/UserOperatorMultiStepForm.tsx
Submit button says "Save and Return to Dashboard" but the click event does not redirect to Dashboard:
![image](https://github.com/bcgov/cas-registration/assets/120038448/a7c1ba46-0ed4-48a4-9003-4477efcfd807)

2024-02-02 14:41 UTC, BCerki commented on client/middlewares/withAuthorization.tsx
Sorry I didn't notice this one! It was a last-minute change and I didn't re-test manually

2024-02-02 14:43 UTC, BCerki commented on client/middlewares/withAuthorization.tsx
I don't understand this one--where would I be returning sentry?

2024-02-02 15:27 UTC, shon-button commented on client/app/components/form/UserOperatorMultiStepForm.tsx
In `client/app/components/form/UserOperatorMultiStepForm.tsx\line 169\isExistingOperator ? "Save and Return to Dashboard" : ""` clicking this button does NOT **return to Dashboard** it displays the screen above; so, perhaps the button should just have text "Save"?

2024-02-02 15:29 UTC, BCerki commented on client/middlewares/withAuthorization.tsx
@shon-button , sorry, linked the wrong one, this sentry one is the one I don't follow

2024-02-02 15:44 UTC, shon-button requested changes

2024-02-02 15:44 UTC, shon-button commented on client/middlewares/withAuthorization.tsx
Sorry for the confusion my copy\paste error, the reference should be: `client/app/utils/actions.ts\export async function actionHandler`

I am asking if the code below could be replaced by using the `actionHandler` utility e.g. `const response = await actionHandler('registration/operator-from-user'...`

```
              const options: RequestInit = {
                cache: "no-store", // Default cache option
                method: "GET",
                headers: new Headers({
                  Authorization: JSON.stringify({
                    user_guid: token.user_guid,
                  }),
                }),
              };
              const response = await fetch(
                `${process.env.API_URL}registration/operator-from-user`,
                options,
              );
```

2024-02-02 15:47 UTC, BCerki commented
Oh, gotcha! I tried using the action handler but I got the build error below so I switched to fetch: 

```
Failed to compile.

./node_modules/@mui/utils/esm/ponyfillGlobal/ponyfillGlobal.js
Dynamic Code Evaluation (e. g. 'eval', 'new Function', 'WebAssembly.compile') not allowed in Edge Runtime 
Learn More: https://nextjs.org/docs/messages/edge-dynamic-code-evaluation
```

2024-02-02 15:48 UTC, BCerki commented on client/middlewares/withAuthorization.tsx
> Sorry for the confusion my copy\paste error, the reference should be: `client/app/utils/actions.ts\export async function actionHandler`
> 
> I am asking if the code below could be replaced by using the `actionHandler` utility e.g. `const response = await actionHandler('registration/operator-from-user'...`
> 
> ```
>               const options: RequestInit = {
>                 cache: "no-store", // Default cache option
>                 method: "GET",
>                 headers: new Headers({
>                   Authorization: JSON.stringify({
>                     user_guid: token.user_guid,
>                   }),
>                 }),
>               };
>               const response = await fetch(
>                 `${process.env.API_URL}registration/operator-from-user`,
>                 options,
>               );
> ```

2024-02-02 15:59 UTC, BCerki commented on client/app/(authenticated)/bceidbusiness/industry_user/dashboard/operations/[operation]/[formSection]/page.tsx
> +// 🚩 flagging that for shared routes between roles, "Page" code is a component for code maintainability
Non-admin industry users should be able to access operations and it looks like the pages weren't in the app yet, so I added here

2024-02-02 21:26 UTC, shon-button reviewed
For your consideration...

2024-02-02 21:26 UTC, shon-button commented on client/app/(authenticated)/dashboard/page.tsx
My concern here would be the possibility of inefficient frontend rendering for user roles that do not require the information from ` const operator = await getOperatorFromUser();` 
An alternative would be to only call ` const operator = await getOperatorFromUser();`  for IO roles: 
e.g.
`client/app/(authenticated)/dashboard/page.tsx`
```

import Tiles from "@/app/components/navigation/Tiles";
import { actionHandler } from "@/app/utils/actions";
import { getServerSession } from "next-auth";
import { authOptions } from "@/app/api/auth/[...nextauth]/route";
import { FrontEndRoles } from "@/app/utils/enums";

export default async function Page() {
  const session = await getServerSession(authOptions);
  const role = session?.user?.app_role || "";
  let status = "";
  switch (role) {
    case FrontEndRoles.INDUSTRY_USER:
    case FrontEndRoles.INDUSTRY_USER_ADMIN:
      const operator = await actionHandler(
        "registration/operator-from-user",
        "GET",
        ""
      );
      status = operator.status;
      break;
  }
  return (
    <div>
      {role === FrontEndRoles.CAS_PENDING ? (
        // Display pending message here
        <MessagePending />
      ) : (
        // Display role based tiles here
        <Tiles role={role} operatorStatus={status} />
      )}
    </div>
  );
}
```
`client/app/components/navigation/Tiles.tsx`
```
"use client";
import Card from "@mui/material/Card";
import CardContent from "@mui/material/CardContent";
import Grid from "@mui/material/Grid";
import Link from "@mui/material/Link";
import Typography from "@mui/material/Typography";
import { FrontEndRoles, OperatorStatus } from "@/app/utils/enums";
import reportAProblemTile from "@/app/data/dashboard/report_a_problem.json";
import bceidSelectOperatorTile from "@/app/data/dashboard/bceid/select_operator.json";
import bceidMyOperatorTile from "@/app/data/dashboard/bceid/my_operator.json";
import bceidOperationsTile from "@/app/data/dashboard/bceid/operations.json";
import bceidUsersTile from "@/app/data/dashboard/bceid/users.json";
import idirOperatorsTile from "@/app/data/dashboard/idir/operators.json";
import idirOperationsTile from "@/app/data/dashboard/idir/operations.json";
import idirUsersTile from "@/app/data/dashboard/idir/users.json";

// 📐 type for ContentItem used to build dashboard content tiles
type ContentItem = {
  title: string;
  content: string;
  links?: { title: string; href: string }[];
};

export default function Tiles({
  role,
  operatorStatus,
}: {
  role: string;
  operatorStatus: string;
}) {
  let contents: ContentItem[] | null = null;
  switch (role) {
    case FrontEndRoles.CAS_ADMIN:
      contents = [
        ...idirOperatorsTile,
        ...idirOperationsTile,
        ...idirUsersTile,
        ...reportAProblemTile,
      ];

      break;
    case FrontEndRoles.CAS_ANALYST:
      contents = [
        ...idirOperatorsTile,
        ...idirOperationsTile,
        ...reportAProblemTile,
      ];
      break;
    case FrontEndRoles.INDUSTRY_USER_ADMIN:
      if (
        operatorStatus === OperatorStatus.PENDING ||
        operatorStatus === OperatorStatus.APPROVED
      ) {
        contents = [
          ...bceidMyOperatorTile,
          ...bceidOperationsTile,
          ...bceidUsersTile,
          ...reportAProblemTile,
        ];
      } else {
        contents = [...bceidSelectOperatorTile, ...reportAProblemTile];
      }
      break;
    case FrontEndRoles.INDUSTRY_USER:
      if (
        operatorStatus === OperatorStatus.PENDING ||
        operatorStatus === OperatorStatus.APPROVED
      ) {
        contents = [
          ...bceidMyOperatorTile,
          ...bceidOperationsTile,
          ...reportAProblemTile,
        ];
      } else {
        contents = [...bceidSelectOperatorTile, ...reportAProblemTile];
      }
      break;
  }

  return (
    <>
      <Grid container>
        {contents &&
          contents.map((content, index) => (
            <Grid
              key={index}
              item
              component={Card}
              xs={12}
              sm={6}
              md={3}
              sx={{
                margin: 6,
                display: "flex",
                flexDirection: "column",
                justifyContent: "space-between",
              }}
            >
              <CardContent data-testid="dashboard-nav-card">
                <Typography variant="h5" component="h2">
                  {content.title}
                </Typography>

                <Typography component="p" color="textSecondary">
                  {content.content}
                </Typography>
              </CardContent>
              {typeof content.links === "object" &&
                content.links.map((link, i) => (
                  <Link
                    key={i}
                    href={link.href}
                    sx={{ textDecoration: "none", padding: "8px" }}
                  >
                    {link.title}
                  </Link>
                ))}
            </Grid>
          ))}
      </Grid>
    </>
  );
}

```

2024-02-06 15:44 UTC, shon-button approved these changes

2024-02-06 16:18 UTC, merged